# Generated by Django 5.1.3 on 2024-11-25 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('checked_option', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_images', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('voice_messages', models.JSONField(blank=True, null=True)),
                ('order_status', models.IntegerField(choices=[(1, 'Designing'), (2, 'Testing'), (3, 'Correction'), (4, 'Delivered')], default=1)),
                ('preview_image', models.URLField(blank=True, max_length=500, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
