# Generated by Django 5.1.3 on 2024-12-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revo', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
