# Generated by Django 5.1.3 on 2024-12-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revo', '0004_alter_order_preview_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
