# Generated by Django 5.1.3 on 2024-12-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revo', '0006_order_notificaation_token_alter_order_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='notification_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
