# Generated by Django 5.1.3 on 2024-12-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revo', '0007_clients_notification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='notificaation_token',
        ),
        migrations.AddField(
            model_name='order',
            name='notification_token',
            field=models.TextField(null=True),
        ),
    ]
