# Generated by Django 5.1.3 on 2024-12-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revo', '0008_remove_order_notificaation_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_order_id',
            field=models.CharField(default=0, editable=False, max_length=20, unique=True, verbose_name='Custom Order ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
    ]
