# Generated by Django 5.1.3 on 2024-12-26 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revo', '0009_order_custom_order_id_alter_order_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangesOtUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('voice_messages', models.FileField(blank=True, null=True, upload_to='update_voice_messages/')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('custom_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_updates', to='revo.order')),
                ('order_preview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_preview_images', to='revo.order')),
            ],
        ),
    ]
