# Generated by Django 5.1.3 on 2024-12-26 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revo', '0010_changesotupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='changesotupdate',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_order_id', to='revo.order'),
            preserve_default=False,
        ),
    ]
