# Generated by Django 5.1.3 on 2024-12-26 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revo', '0011_changesotupdate_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changesotupdate',
            name='custom_order',
        ),
        migrations.RemoveField(
            model_name='changesotupdate',
            name='order_preview',
        ),
        migrations.AlterField(
            model_name='changesotupdate',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='revo.order'),
        ),
    ]
